[package]
name = "blockchain"
version = "0.1.0"
authors = ["10thfloor <remember.mackenzie@gmail.com>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
sha2 = "0.10.9"
