[package]
name = "blockchain"
version = "0.1.0"
authors = ["10thfloor <remember.mackenzie@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
sha2 = "0.8.1"
